services:
  - type: web
    name: fastfood-api
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install --upgrade pip
      pip install -r requirements.txt
      alembic upgrade head
    startCommand: |
      cd backend
      uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: API_PREFIX
        value: /v1
      - key: PROJECT_NAME
        value: FastFood API
      - key: VERSION
        value: 1.0.0
      - key: LOG_LEVEL
        value: INFO 