apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
  namespace: fastfood
data:
  # Database Configuration
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/fastfood"
  
  # Environment
  ENVIRONMENT: "production"
  DEBUG: "false"
  
  # API Configuration
  API_PREFIX: "/v1"
  PROJECT_NAME: "FastFood API"
  VERSION: "1.0.0"
  
  # Logging
  LOG_LEVEL: "INFO"
  
  # CORS Configuration
  CORS_ALLOW_ORIGINS: "https://fastfood.vercel.app" 