apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postech-fase2

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres-persistent-volume.yaml
- postgres-deployment.yaml
- app-deployment.yaml
- hpa.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: postech-fase2
  app.kubernetes.io/version: v2.0.0 